name: Ubuntu ssh Virtual Machine (ioi)
on: 
  workflow_dispatch:
  # schedule:
    # - cron: '0 */6 * * *'

defaults:
  run:
    shell: bash
  
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
#    - name: If failed, means ok
#      run: ./not-exist-file.sh it bloke build
    - name: Preparing Linux Environment
      run: sudo apt-get update
    - name: Setting Up the Ubuntu Environment
    #  if: ${{ failure() }}
      run: bash linux-ssh.sh
      env:
        LINUX_USER_PASSWORD: ${{ secrets.LINUX_USER_PASSWORD }}
        LINUX_MACHINE_NAME: ${{ secrets.LINUX_MACHINE_NAME }}
        LINUX_USERNAME: ${{ secrets.LINUX_USERNAME }}
    - name: Setting Up the XRay
    #  if: ${{ failure() }}
      run: |
        sudo bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install -u root
        echo $XRAY_CONFIG | sudo tee /usr/local/etc/xray/config.json
        sudo openssl ecparam -name prime256v1 -genkey -out /home/private.key
        sudo openssl req -new -x509 -days 7305 -key /home/private.key -out /home/fullchain.crt -subj "/C=CN/ST=Beijing/L=Beijing/O=Beijing OnlineJudge Technology Co., Ltd./OU=Service Infrastructure Department/CN=`hostname`"
        sudo systemctl restart xray
      env:
        XRAY_CONFIG: ${{ secrets.XRAY_CONFIG }}
    - name: Setting Up the ioi
    #  if: ${{ failure() }}
      run: |
        sudo wget -q -O ioi https://github.com/Harry-zklcdc/ioi/blob/master/ioi_linux_x64?raw=true
        sudo chmod +x ./ioi
        sudo sysctl -w net.core.rmem_max=2500000 && sudo sysctl -p
        sudo nohup ./ioi > ioi.log 2>&1 &
        sudo passwd=`head -n 4 ioi.log | tail -n 1` && passwd=${passwd##*:} && passwd=${passwd% *}
        sudo ps aux | grep ioi
        sudo echo passwd
        sudo curl -X PUT -d "proto=tcp&port=22&password=${passwd}" "127.0.0.1:10101/api/port"
        sudo curl -X PUT -d "proto=tcp&port=443&password=${passwd}" "127.0.0.1:10101/api/port"
        ID=`sudo head -n 3 ioi.log | sudo tail -n 1` && ID=${ID##*warn}
        echo
        echo ########## ioi ID ##########
        echo $ID
        echo
        head -n 18 ioi.log
    - name: Keep Running Ubuntu System and keepAlive
     # if: ${{ failure() }}
      run: sleep 6h
